from prism_kondo.instance_selection import (
    DROP2RE,
    DROP2RT,
    DROP3RE,
    DROP3RT,
    Fish1Selector,
    Fish2Selector,
    FixedTimeSelector,
    FullSetSelector,
    GradientShapleySelector,
    LOFSelector,
    MutualInformationSelector,
    RandomSelector,
    RegCnnSelector,
    RegEnnSelector,
    RegENNSelectorTime,
    SelconSelector,
)

SELECTOR_DICT = {
    "reg_enn": RegEnnSelector,
    "reg_enn_time": RegENNSelectorTime,
    "reg_cnn": RegCnnSelector,
    "drop_two_re": DROP2RE,
    "drop_two_rt": DROP2RT,
    "drop_three_re": DROP3RE,
    "drop_three_rt": DROP3RT,
    "mutual_information": MutualInformationSelector,
    "fish1": Fish1Selector,
    "fish": Fish2Selector,
    "shapley": GradientShapleySelector,
    "selcon": SelconSelector,
    "fixed_window": FixedTimeSelector,
    "random": RandomSelector,
    "full": FullSetSelector,
    "lof": LOFSelector,
}


SELECTOR_NAMES = [
    "reg_enn",
    "reg_enn_time",
    "reg_cnn",
    "drop_two_re",
    "drop_two_rt",
    "drop_three_re",
    "drop_three_rt",
    "mutual_information",
    "fish",
    "fish1" "shapley",
    "selcon",
    "fixed_window",
    "random",
    "lof",
]
SELECTOR_NAMES_DISPLAY = {
    "reg_enn": "RegENN",
    "reg_enn_time": "RegENNTime",
    "reg_cnn": "RegCNN",
    "drop_two_rt": "DROP2RT",
    "drop_two_re": "DROP2RE",
    "drop_three_rt": "DROP3RT",
    "drop_three_re": "DROP3RE",
    "mutual_information": "MI",
    "fish": "FISH",
    "fish1": "FISH1",
    "shapley": "Shapley",
    "selcon": "SelCon",
    "fixed_window": "Fixed Window",
    "lof": "LOF",
    "ground_truth": "Ground Truth",
    "full": "Full Set",
}
COMPANIES = [
    "amoeneburg",
    "maerker",
    "rohrdorfer",
    "spenner",
    "woessingen",
]
STANDARD_COLUMNS = [
    "slug",
    "exported_at",
    "recorded_at",
    "cement_slug",
    "sample_type_slug",
]
COMPANY_FEATURES = {
    "spenner": [
        "robolab__psd_computed__perc_63_2",
        "robolab__psd_computed__perc_10",
        "robolab__psd_computed__perc_16",
        "robolab__psd_computed__perc_50",
        "robolab__psd_computed__perc_84",
        "robolab__psd_computed__perc_90",
        "robolab__psd_computed__perc_95",
        # always the same
        # "robolab__psd__q_000_3",
        "robolab__psd__q_000_7",
        "robolab__psd__q_001",
        "robolab__psd__q_010",
        "robolab__psd__q_112",
        "robolab__psd__q_012",
        # no variance
        # "robolab__psd__q_140",
        "robolab__psd__q_015",
        # no variance
        # "robolab__psd__q_180",
        "robolab__psd__q_002",
        "robolab__psd__q_020",
        # no variance
        # "robolab__psd__q_224",
        "robolab__psd__q_025",
        # no variance
        # "robolab__psd__q_280",
        "robolab__psd__q_003",
        # no variance
        # "robolab__psd__q_315",
        "robolab__psd__q_032",
        "robolab__psd__q_036",
        "robolab__psd__q_003_2",
        "robolab__psd__q_004",
        "robolab__psd__q_045",
        "robolab__psd__q_005",
        "robolab__psd__q_050",
        "robolab__psd__q_056",
        "robolab__psd__q_006",
        "robolab__psd__q_063",
        "robolab__psd__q_007",
        "robolab__psd__q_008",
        "robolab__psd__q_009",
        "robolab__psd__q_090",
        "robolab__psd__r_090",
        "robolab__psd__r_200",
        "robolab__psd_computed__slope",
        "robolab__xrd__c3s_m1",
        "robolab__xrd__c3s_m3",
        "robolab__xrd_computed__fraction_m1",
        "robolab__xrd__anhydrite",
        "robolab__xrd__arcanite",
        "robolab__xrd__bassanite",
        "robolab__xrd__c2s_alpha",
        "robolab__xrd__c2s_beta",
        "robolab__xrd__c2s_sum",
        "robolab__xrd__c3a_cubic",
        "robolab__xrd__c3a_ortho",
        "robolab__xrd__c3s_sum",
        # changes with grinding aid
        # "robolab__xrd__c3s_crystalsize",
        "robolab__xrd__c4af",
        "robolab__xrd__calcite",
        # computed feature
        # "robolab__xrd_computed__co2",
        "robolab__xrd__dolomite",
        # "robolab__xrd__flyash", in linear_features_exclude
        "robolab__xrd__lime",
        "robolab__xrd__gypsum",
        "robolab__xrd__slag_amorphous",
        # computed feature
        # "robolab__xrd_computed__limestone_sulfate_free",
        "robolab__xrd__periclase",
        "robolab__xrd__portlandite",
        "robolab__xrd__quartz",
        # "robolab__xrd_computed__r_wp",
        # computed feature
        # "robolab__xrd_computed__so3",
        "robolab__xrf__al2o3",
        # computed features
        # "robolab__xrf_computed__c2s",
        # "robolab__xrf_computed__c3a",
        # 'robolab__xrf_computed__c3s',
        # "robolab__xrf_computed__c4af",
        "robolab__xrf__cao",
        "robolab__xrf__cl",
        "robolab__xrf__fe2o3",
        # computed features
        # "robolab__xrf_computed__slag_amorphous",
        # "robolab__xrf_computed__slag_amorphous_sulfate_free",
        "robolab__xrf__k2o",
        "robolab__xrf__mgo",
        "robolab__xrf__mno",
        "robolab__xrf__na2o",
        # "robolab__xrf_computed__na2o_equivalent",
        "robolab__xrf__p2o5",
        "robolab__xrf__sulfide",
        "robolab__xrf__sio2",
        "robolab__xrf__so3",
        "robolab__xrf__tio2",
        # "robolab__xrf_computed__trass",
    ],
    "woessingen": [
        "robolab__psd__r_000_25",
        "robolab__psd__r_000_4",
        "robolab__psd__r_000_63",
        "robolab__psd__r_000_8",
        "robolab__psd__r_001",
        "robolab__psd__r_001_6",
        "robolab__psd__r_002_5",
        "robolab__psd__r_003_2",
        "robolab__psd__r_005",
        "robolab__psd__r_008",
        "robolab__psd__r_015",
        "robolab__psd__r_016",
        "robolab__psd__r_025",
        "robolab__psd__r_032",
        "robolab__psd__r_036",
        "robolab__psd__r_040",
        "robolab__psd__r_045",
        "robolab__psd__r_050",
        "robolab__psd__r_056",
        "robolab__psd__r_063",
        "robolab__psd__r_071",
        "robolab__psd__r_080",
        "robolab__psd__r_090",
        # are almost always 0
        # "robolab__psd__r_100",
        # "robolab__psd__r_112",
        # "robolab__psd__r_125",
        # "robolab__psd__r_140",
        # "robolab__psd__r_160",
        # "robolab__psd__r_180",
        # "robolab__psd__r_200",
        "robolab__psd_computed__perc_10",
        "robolab__psd_computed__perc_50",
        "robolab__psd_computed__perc_63_2",
        "robolab__psd_computed__perc_90",
        "robolab__psd_computed__slope",
        "robolab__xrd__anhydrite",
        # not enough data
        # "robolab__xrd__aphtitalite",
        "robolab__xrd__arcanite",
        "robolab__xrd__bassanite",
        "robolab__xrd__c2s_alpha",
        # not enough data
        # "robolab__xrd__c2s_alpha_h",
        "robolab__xrd__c2s_beta",
        # not enough data
        # "robolab__xrd__c2s_gamma",
        "robolab__xrd__c2s_sum",
        "robolab__xrd__c3a_cubic",
        "robolab__xrd__c3a_ortho",
        "robolab__xrd__c3a_sum",
        # "robolab__xrd__c3s_m1", only for some cems
        # "robolab__xrd__c3s_m3", only for some cems
        "robolab__xrd__c3s_sum",
        "robolab__xrd__c4af",
        "robolab__xrd__calcite",
        "robolab__xrd__gypsum",
        # not enough data
        # "robolab__xrd__hematite",
        "robolab__xrd__langbeinite",
        # not enough data
        # "robolab__xrd__magnetite",
        # "robolab__xrd__mullite",
        "robolab__xrd__periclase",
        "robolab__xrd__portlandite",
        "robolab__xrd__quartz",
        # "robolab__xrd__slag_amorphous", only for some cems
        # not useful computed features, except for fraction
        # "robolab__xrd_computed__co2",
        # "robolab__xrd_computed__fraction_m1", only for some cems
        # "robolab__xrd_computed__freelime",
        # "robolab__xrd_computed__r_wp",
        # "robolab__xrd_computed__so3",
        "robolab__xrf__al2o3",
        "robolab__xrf__cao",
        "robolab__xrf__cl",
        "robolab__xrf__fe2o3",
        "robolab__xrf__k2o",
        "robolab__xrf__mgo",
        # "robolab__xrf__mno", only for some cems
        "robolab__xrf__na2o",
        "robolab__xrf__sio2",
        "robolab__xrf__so3",
        # "robolab__xrf__sulfide", only for some cems
        # "robolab__xrf__tio2", only for some cems
        # not useful computed features
        # "robolab__xrf_computed__c2s",
        # "robolab__xrf_computed__c3a",
        # "robolab__xrf_computed__c3s",
        # "robolab__xrf_computed__c4af",
        # "robolab__xrf_computed__limestone_sulfate_free",
        # "robolab__xrf_computed__na2o_equivalent",
    ],
    "rohrdorfer": [
        "robolab__psd_computed__perc_10",
        "robolab__psd_computed__perc_50",
        "robolab__psd_computed__perc_90",
        # evil! seems to be corrupted in March 2021
        # "robolab__psd_computed__blaine",
        "robolab__psd_computed__slope",
        "robolab__psd_computed__perc_63_2",
        "robolab__xrf__so3",
        "robolab__xrf__sio2",
        "robolab__xrf__cl",
        "robolab__xrf__cao",
        "robolab__xrf__fe2o3",
        "robolab__xrf__k2o",
        "robolab__xrf__mgo",
        "robolab__xrf__na2o",
        "robolab__xrf__al2o3",
        "robolab__xrd__anhydrite",
        "robolab__xrd__c3s_m3",
        "robolab__xrd__c3s_sum",
        "robolab__xrd__c3a_cubic",
        "robolab__xrd__c3a_ortho",
        "robolab__xrd__c3a_sum",
        "robolab__xrd__aphthitalite",
        "robolab__xrd__arcanite",
        "robolab__xrd__c2s_beta",
        "robolab__xrd__calcite",
        "robolab__xrd__dolomite",
        "robolab__xrd__c4af",
        "robolab__xrd__bassanite",
        "robolab__xrd__lime",
        "robolab__xrd__langbeinite",
        "robolab__xrd__periclase",
        "robolab__xrd__quartz",
        # do not use xrd computed features
        # "robolab__xrd_computed__freelime",
        "robolab__xrd__slag_amorphous",
        "robolab__xrd__gypsum",
        "robolab__xrd__portlandite",
    ],
    "maerker": [
        "robolab__psd__r_001",
        "robolab__psd__r_001_5",
        "robolab__psd__r_001_8",
        "robolab__psd__r_002",
        "robolab__psd__r_002_2",
        "robolab__psd__r_002_6",
        "robolab__psd__r_003",
        "robolab__psd__r_003_6",
        "robolab__psd__r_004",
        "robolab__psd__r_004_4",
        "robolab__psd__r_005_2",
        "robolab__psd__r_006",
        "robolab__psd__r_006_2",
        "robolab__psd__r_007_4",
        "robolab__psd__r_008",
        "robolab__psd__r_008_6",
        "robolab__psd__r_010",
        "robolab__psd__r_012",
        "robolab__psd__r_015",
        "robolab__psd__r_016",
        "robolab__psd__r_018",
        "robolab__psd__r_021",
        "robolab__psd__r_024",
        "robolab__psd__r_025",
        "robolab__psd__r_030",
        "robolab__psd__r_032",
        "robolab__psd__r_036",
        "robolab__psd__r_042",
        "robolab__psd__r_045",
        "robolab__psd__r_050",
        "robolab__psd__r_060",
        "robolab__psd__r_064",
        "robolab__psd__r_072",
        "robolab__psd__r_086",
        "robolab__psd__r_090",
        "robolab__psd__r_102",
        "robolab__psd__r_120",
        "robolab__psd__r_122",
        "robolab__psd__r_146",
        "robolab__psd__r_160",
        "robolab__psd__r_174",
        "robolab__psd__r_180",
        "robolab__psd__r_206",
        "robolab__psd__r_212",
        "robolab__psd__r_246",
        "robolab__psd__r_264",
        "robolab__psd__r_294",
        "robolab__psd__r_300",
        "robolab__psd__r_350",
        "robolab__psd__r_500",
        "robolab__psd_computed__perc_10",
        "robolab__psd_computed__perc_50",
        "robolab__psd_computed__perc_63_2",
        "robolab__psd_computed__perc_90",
        "robolab__psd_computed__slope",
        "robolab__xrd__anhydrite",
        "robolab__xrd__arcanite",
        "robolab__xrd__bassanite",
        "robolab__xrd__c2s_sum",
        "robolab__xrd__c3a_cubic",
        "robolab__xrd__c3a_ortho",
        "robolab__xrd__c3s_sum",
        "robolab__xrd__c4af",
        "robolab__xrd__calcite",
        "robolab__xrd__dolomite",
        "robolab__xrd__gypsum",
        "robolab__xrd__langbeinite",
        "robolab__xrd__lime",
        "robolab__xrd__periclase",
        "robolab__xrd__portlandite",
        "robolab__xrd__quartz",
        # "robolab__xrd__slag_amorphous", not in df
        "robolab__xrf__al2o3",
        "robolab__xrf__cao",
        "robolab__xrf__cl",
        # "robolab__xrf__cr2o3",
        "robolab__xrf__fe2o3",
        "robolab__xrf__k2o",
        "robolab__xrf__mgo",
        "robolab__xrf__na2o",
        "robolab__xrf__sio2",
        "robolab__xrf__so3",
        # "robolab__xrf__tio2",
        "robolab__xrf_computed__na2o_equivalent",
    ],
    "amoeneburg": [
        "robolab__psd__q_000_9",
        "robolab__psd__q_001_1",
        "robolab__psd__q_001_3",
        "robolab__psd__q_001_5",
        "robolab__psd__q_001_8",
        "robolab__psd__q_002_2",
        "robolab__psd__q_002_6",
        "robolab__psd__q_003_1",
        "robolab__psd__q_003_7",
        "robolab__psd__q_004_3",
        "robolab__psd__q_005",
        "robolab__psd__q_006",
        "robolab__psd__q_007_5",
        "robolab__psd__q_009",
        "robolab__psd__q_010_5",
        "robolab__psd__q_012",
        "robolab__psd__q_015",
        "robolab__psd__q_018",
        "robolab__psd__q_021",
        "robolab__psd__q_025",
        "robolab__psd__q_030",
        "robolab__psd__q_036",
        "robolab__psd__q_043",
        "robolab__psd__q_051",
        "robolab__psd__q_061",
        "robolab__psd__q_073",
        "robolab__psd__q_087",
        "robolab__psd__q_103",
        "robolab__psd__q_123",
        "robolab__psd__q_147",
        "robolab__psd__r_040",
        "robolab__psd__r_043",
        "robolab__psd__r_045",
        "robolab__psd_computed__perc_63_2",
        "robolab__psd_computed__slope",
        "robolab__xrf__al2o3",
        "robolab__xrf__cao",
        "robolab__xrf__cl",
        "robolab__xrf__cr2o3",
        "robolab__xrf__fe2o3",
        "robolab__xrf__k2o",
        "robolab__xrf__mgo",
        "robolab__xrf__mno",
        "robolab__xrf__na2o",
        "robolab__xrf__p2o5",
        "robolab__xrf__sio2",
        "robolab__xrf__so3",
        # "robolab__xrf__sulfide", exclude linear in config
        "robolab__xrf__tio2",
        # "robolab__xrd__amorphous_white_clinker", exclude linear in config
        "robolab__xrd__anhydrite",
        "robolab__xrd__arcanite",
        "robolab__xrd__bassanite",
        "robolab__xrd__c2s_beta",
        "robolab__xrd__c2s_sum",
        "robolab__xrd__c3a_cubic",
        "robolab__xrd__c3a_ortho",
        "robolab__xrd__c3a_sum",
        "robolab__xrd__c3s_m1",
        "robolab__xrd__c3s_m3",
        "robolab__xrd__c3s_sum",
        # "robolab__xrd__c4af", exclude linear in config
        "robolab__xrd__calcite",
        # "robolab__xrd__gypsum", exclude linear in config
        "robolab__xrd__periclase",
        # "robolab__xrd__portlandite", exclude linear in config
        # "robolab__xrd__quartz", exclude linear in config
        # "robolab__xrd__slag_amorphous", exclude linear in config
        "robolab__xrd_computed__freelime",
        "lab__carbon_sulfur_analyzer__co2",
        "lab__carbon_sulfur_analyzer__so3",
        # "lab__color__a",  exclude linear in config
        # "lab__color__b", exclude linear in config
        # "lab__color__l", exclude linear in config
        # "robolab__xrf_computed__al_h_comp", exclude linear in config
        # "robolab__xrf_computed__al_nh_comp", exclude linear in config
        # "robolab__xrf_computed__sio2_up_comp", exclude linear in config
    ],
}
MIN_DATES = {
    "spenner": "2019-01-01",
    "woessingen": "2019-06-01",
    "amoeneburg": "2021-04-28",
    "rohrdorfer": "2020-02-01",
    "maerker": "2020-08-18",
}
MAX_DATES = {
    "spenner": None,
    "woessingen": "2022-08-01",
    "amoeneburg": None,
    "rohrdorfer": None,
    "maerker": None,
}
# 28d prod, because shipment config always has 2d cs
MAX_NAN_ROW_RATIO_28d_PROD = {
    "spenner": 0.30214822596444635,  # only iii model in config
    "amoeneburg": 0.31225539463742497,
    "woessingen": 0.35,  # no info in config
    "maerker": 0.5738625935628094,
    "rohrdorfer": 0.3,
}
PCA_N_COMPONENTS = 0.9

PCA_FEATURE_KEYWORDS = {
    "spenner": [],
    "rohrdorfer": ["psd_computed"],
    "amoeneburg": ["psd_computed"],
    "maerker": ["psd_computed"],
    "woessingen": ["psd__"],
}
COMPANY_ANONYMIZER = {
    "amoeneburg": "Company 1",
    "maerker": "Company 2",
    "rohrdorfer": "Company 3",
    "spenner": "Company 4",
    "woessingen": "Company 5",
}
